name: 'cubo_158'
version: '1.0.0'
config-version: 2
profile: 'cubo_158'
model-paths: ["models"]
macro-paths: ["macros"]
seed-paths: ["seeds"]
target-path: "target"
clean-targets: ["target"]
models:
  cubo_158:
    staging:
      +materialized: view
    marts:
      +materialized: table
